### PR TITLE
2023.06.1

### PR DESCRIPTION
**Pull request by j-wags**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by j-wags** [comment]
@conda-forge-admin, please rerender

**Review by mattwthompson — APPROVED** [review]
I wouldn't hurt to update `python >=3.6`, though I won't push too strongly for it. (I'd almost prefer no constraint over "don't use an extremely ancient version, just a sort crusty one")

**Comment by j-wags** [comment]
Huh, TIL. I'll leave it at >=3.6 since that seems closest to my preferred solution ("don't pin")

**Comment by mattwthompson** [comment]
3.6 fine but I'm 90% sure that bot comment is something that was manually written ~3 years ago and hasn't been updated since

**Pull request merged**
